name: Build CV
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: "1.40.0"

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: "0.13.1"

      - name: Build
        run: just build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Files
          path: |
            cv.pdf
            documents/*
            references/*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            cv.pdf
            documents/*
            references/*
