name: Build CV
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
          extra_fonts: ./vendored/DevIconsLatex/devicons/fonts/devicon.ttf

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Files
          path: |
            cv.pdf
            documents/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cv.pdf
            documents/*
